# Generated by Django 5.0.2 on 2024-03-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="isActive",
            field=models.BooleanField(default=False),
        ),
    ]
